#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "====== start pre-commit by husky ======"

lint_output=$(yarn lint)

# eslint 경고가 있는지 및 "Warning" 단어 확인
if  echo "$lint_output" | grep -q "Warning"; then
  echo "eslint warning이 발생했습니다. 커밋을 취소합니다."
  echo "$lint_output"
  echo "====== failed pre-commit by husky ======"
  exit 1
fi

echo "====== end pre-commit by husky ======"